---
- hosts: all
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: host-defaults

- hosts: gluster_nodes
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: gluster
  tags: gluster   