---
- hosts: all
  order: sorted
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: host-defaults

- hosts: swarm_managers
  order: sorted
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: docker
    - import_role:
        name: swarm-managers

- hosts: swarm_workers
  order: sorted
  gather_facts: false
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: docker
    - import_role:
        name: swarm-workers

- hosts: gluster_nodes
  order: sorted
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: gluster
  tags: gluster   
  
- hosts: swarm_managers
  order: sorted
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: traefik
    - import_role:
        name: portainer

- hosts: haproxy
  order: sorted
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: haproxy
  tags: haproxy