---
- hosts: gluster_nodes
  become: true
  become_method: sudo
  tasks:
    - name: Disable Gluster service
      systemd:
        name: glusterd
        enabled: no
        state: stopped

    - name: Uninstall Gluster and dependencies
      become: true
      become_method: sudo
      apt:
        pkg:
          - glusterfs-server
          - glusterfs-common
          - glusterfs-client
        state: absent
      register: uninstall
      
    - debug:
        var: uninstall.stdout_lines 